# Static configuration
# https://docs.traefik.io/reference/static-configuration/file/

global:
  checkNewVersion: false
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true
  maxIdleConnsPerHost: "10"
  forwardingTimeouts:
    dialTimeout: "30s"
    responseHeaderTimeout: "30s"
    idleConnTimeout: "180s"

entryPoints:
  http:
    address: ":80"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: "30s"
        graceTimeOut: "30s"
      respondingTimeouts:
        readTimeout: "30s"
        writeTimeout: "30s"
        idleTimeout: "360s"
  https:
    address: ":443"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: "30s"
        graceTimeOut: "30s"
      respondingTimeouts:
        readTimeout: "30s"
        writeTimeout: "30s"
        idleTimeout: "360s"
  tcp29418:
    address: ":29418"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: "30s"
        graceTimeOut: "30s"
      respondingTimeouts:
        readTimeout: "30s"
        writeTimeout: "30s"
        idleTimeout: "360s"
log:
  level: "INFO" # DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  filePath: "/logs/traefik/traefik.log"
  format: "common"

accessLog:
  filePath: "/logs/traefik/access.log"
  format: "common"
  bufferingSize: "100"
#   fields:
#     defaultMode: "keep"
#     headers:
#       defaultMode: "keep"
#       names:
#           # User-Agent: redact
#           Authorization: drop
#           # Content-Type: keep

api:
  insecure: true
  dashboard: true
  debug: false

ping:
  entryPoint: "traefik"

providers:
  providersThrottleDuration: "2s"
  file:
    filename: "/etc/traefik/traefik.dynamic.yml"
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    swarmMode: true
    # useBindPortIP: false
    exposedByDefault: false
    network: "proxy"
    swarmModeRefreshSeconds: "15s"
  rest:
    insecure: true