version: "3.7"

services:
  pg:
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg-pwd
    secrets:
      - pg-pwd
    volumes:
      - /mnt/pg-vol/data:/var/lib/postgresql/data
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker
  pgadmin:
    image: dpage/pgadmin4:2023-10-17-1
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pg-pwd
    secrets:
      - pg-pwd
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.adminer.rule=Host(`pg-admin.example.com`)"
        - "traefik.http.routers.adminer.entrypoints=http"
        - "traefik.http.routers.adminer.service=adminer"
        - "traefik.http.services.adminer.loadbalancer.server.port=80"
networks:
  proxy:
    external: true
secrets:
  pg-pwd:
    external: true