version: "3.7"

services:
  ldap:
    image: osixia/openldap:1.5.0
    secrets:
      - ldap-admin-pwd
    networks:
      - proxy
    environment:
      LDAP_ORGANISATION: "Example"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD_FILE: /run/secrets/ldap-admin-pwd
    volumes:
      - /mnt/ldap-vol/var:/var/lib/ldap
      - /mnt/ldap-vol/etc:/etc/ldap/slapd.d
  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    networks:
      - proxy
    ports:
      - "6443:443"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.ldap-admin.rule=Host(`ldap-admin.example.com`)"
        - "traefik.http.routers.ldap-admin.entrypoints=https"
        - "traefik.http.routers.ldap-admin.tls=true"
        - "traefik.http.routers.ldap-admin.service=ldap-admin"
        - "traefik.http.services.ldap-admin.loadbalancer.server.port=443"
networks:
  proxy:
    external: true
secrets:
  ldap-admin-pwd:
    external: true